categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts

pagination:
    prev_text: Prev
    next_text: Next
footer:
    powered: Power by
    theme: Theme By